[program:canvas-ws]
command=php /var/www/canvas/ws/server.php
directory=/var/www/canvas
autostart=true
autorestart=true
startretries=10
startsecs=2
stopwaitsecs=10
stderr_logfile=/var/log/canvas-ws.err.log
stdout_logfile=/var/log/canvas-ws.out.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
user=www-data
environment=HOME="/var/www",USER="www-data"
